#!/bin/bash

function out {
	echo "${1}"
        exit 1
}

[[ $(id -u) -eq 0 ]] || out "Needs Root!"

[[ ${1} == "shecan" ]] && echo -e "nameserver 178.22.122.100\nnameserver 185.51.200.2" > /etc/resolv.conf && out "Shecan DNS!"

[[ ${1} == "403" ]] && echo -e "nameserver 10.202.10.202\nnameserver 10.202.10.102" > /etc/resolv.conf && out "403 DNS!"

echo -e "nameserver 1.1.1.1\nnameserver 8.8.4.4" > /etc/resolv.conf && out "Public DNS!"

