#!/bin/bash

host="HOST"
config=$(echo ~/.ssh/config)
switch="${1}"

function current {
    echo $(pgrep -f "ssh -o StrictHostKeyChecking=no -N -f -D 1080 ${host} -F ${config}")
}

function start {
    [[ $(current) == "" ]] && ssh -o StrictHostKeyChecking=no -N -f -D 1080 ${host} -F ${config}
}

function stop {
    pid=$(current)
    [[ "${pid}" == "" ]] || kill -9 "${pid}"
}

function status() {
    pid=$(current)
    ([[ "${pid}" == "" ]] && echo "Not Connected!") || echo "Connected - PID: ${pid}"
}

function restart {
    stop
    sleep 3
    start
}

function cron {
    state="${1}"
    if [ "${state}" == "on" ]; then
        echo "* * * * * tunnel start" | crontab -
        echo "Cron gets UP!"
    elif [ "${state}" == "off" ]; then
        crontab -l | sed '/tunnel start/d' | crontab -
        echo "Cron gets DOWN!"
    else
        exists=$(crontab -l | grep "tunnel start")
        ([[ "${exists}" ]] && echo "UP!") || echo "DOWN!"
    fi
}

if [ "${switch}" == "start" ]; then
    start
elif [ "${switch}" == "restart" ]; then
    restart
elif [ "${switch}" == "stop" ]; then
    stop
elif [ "${switch}" == "cron" ]; then
    cron "${2}"
else
    status
fi
