#!/bin/bash

host="HOST"
config=$(echo ~/.ssh/config)
switch="${1}"

function current {
    echo $(pgrep -f "ssh -o StrictHostKeyChecking=no -N -f -D 1080 ${host} -F ${config}")
}

function start {
    [[ $(current) == "" ]] && ssh -o StrictHostKeyChecking=no -N -f -D 1080 ${host} -F ${config}
}

function stop {
    pid=$(current)
    [[ "${pid}" == "" ]] || kill -9 "${pid}"
}

function status() {
    pid=$(current)
    ([[ "${pid}" == "" ]] && echo "Not Connected!") || echo "Connected - PID: ${pid}"
}

function restart {
    stop
    sleep 3
    start
}

if [ "${switch}" == "start" ]; then
    start
elif [ "${switch}" == "restart" ]; then
    restart
elif [ "${switch}" == "stop" ]; then
    stop
else
    status
fi
